name: Application Insights Native Metrics Linux Alpine CI
on:
  push:
    branches:
      - hectorhdzg/alpine
env:
  NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        node-version: [12, 14, 16, 18, 20]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build:ts
      - run: npm run build
      - run: npm run package
       # Generate musl binaries using Alpine Linux
      - run: docker build --build-arg VERSION=${{ matrix.node-version }} -t tmp/alpine-native-metrics .;
      - run: docker run -e NODE_PRE_GYP_GITHUB_TOKEN tmp/alpine-native-metrics;
      - uses: actions/upload-artifact@v2
        with:
          name: linux_alpine_artifact_${{ matrix.node-version }}
          path: build/stage/
          retention-days: 1