name: Application Insights Native Metrics Linux CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

env:
  CXX: g++-4.8
  NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: apt-get update \
          && apt-get python \
          && apt-get python-dev \
          && apt-get py-pip \
          && apt-get build-base \
          && pip install virtualenv \
          && rm -rf /var/cache/apk/*

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo 'C++ Version'; $CXX --version;
      - run: npm ci
      - run: npm run build:ts
      - run: npm run build
      - run: npm test
      - run: npm run publish:github
