name: Application Insights Native Metrics Linux CI
on:
  push:
    tags:
      - 'v*'
env:
  NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12, 14, 15, 16, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:ts
      - run: npm run build
      - run: if [[ ${{ matrix.node-version }} == 14 ]]; then npm run lint; fi;
      - run: npm run package
      - uses: actions/upload-artifact@v2
        with:
          name: linux_artifact_${{ matrix.node-version }}
          path: build/stage/
          retention-days: 1
      - name: Publish
      # Publish not compatible with node 8, need to manually upload the files
        if: ${{ matrix.node-version != '8' }}
        run: npm run publish:github
      # Generate musl binaries using Alpine Linux
      # TODO: mhart/alpine-node:17 not currently available 
      # TODO: mhart/alpine-node:15 fails to install virtualenv 
      - run: if [[ ${{ matrix.node-version }} != 8 &&  ${{ matrix.node-version }} != 15 &&  ${{ matrix.node-version }} != 17 ]]; then docker build --build-arg VERSION=${{ matrix.node-version }} -t tmp/alpine-native-metrics .; fi;
      - run: if [[ ${{ matrix.node-version }} != 8 &&  ${{ matrix.node-version }} != 15 &&  ${{ matrix.node-version }} != 17 ]]; then docker run -e NODE_PRE_GYP_GITHUB_TOKEN tmp/alpine-native-metrics; fi;
