name: Application Insights Native Metrics Linux CI
on:
  push:
    branches:
      - jacksonweber/fix-linux-binaries
env:
  NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        node-version: [8, 10, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: apk add --no-cache build-base g++ cairo-dev jpeg-dev pango-dev giflib-dev
      - run: apk add --update --repository http://dl-3.alpinelinux.org/alpine/edge/testing libmount ttf-dejavu ttf-droid ttf-freefont ttf-liberation fontconfig
      - run: npm install
      - run: npm run build:ts
      - run: npm run build
      - run: npm run package
      - uses: actions/upload-artifact@v2
        with:
          name: linux_artifact_${{ matrix.node-version }}
          path: build/stage/
          retention-days: 1
      - name: Publish
      # Publish not compatible with node 8, need to manually upload the files
        if: ${{ matrix.node-version != '8' }}
        run: npm run publish:github