name: Application Insights Native Metrics Linux CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

env:
  NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:ts
      - run: npm run build
      - run: npm test
      - run: npm run publish:github
       # Setup docker
      - run: docker build --build-arg VERSION=${{ matrix.node-version }} -t tmp/alpine-native-metrics
      # Generate musl binaries using Alpine Linux
      - run: docker run -e NODE_PRE_GYP_GITHUB_TOKEN tmp/alpine-native-metrics

      

