name: Application Insights Native Metrics Linux CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

env:
  NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12, 14, 15, 16, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:ts
      - run: npm run build
      - run: npm test
      - run: npm run package
      - uses: actions/upload-artifact@v2
        with:
          name: linux_artifact
          path: build/stage/
      - name: Publish
        if: ${{ matrix.node-version != '8' }}
        run: npm run publish:github
      # Generate musl binaries using Alpine Linux
      - run: if [[ ${{ matrix.node-version }} != "8" ]]; then docker build --build-arg VERSION=${{ matrix.node-version }} -t tmp/alpine-native-metrics . fi;
      - run: if [[ ${{ matrix.node-version }} != "8" ]]; then docker run -e NODE_PRE_GYP_GITHUB_TOKEN tmp/alpine-native-metrics; fi;

      

