name: Application Insights Native Metrics MacOS CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

env:
  LINUX_CXX: g++-4.8
  NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [8, 10, 12, 14, 15, 16, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:ts
      - run: npm run build
      - run: npm test
      - run: npm run package
      - uses: actions/upload-artifact@v2
        with:
          name: macos_artifact_${{ matrix.node-version }}
          path: build/stage/
          retention-days: 1
      - name: Publish
        if: ${{ matrix.node-version != '8' }}
        run: npm run publish:github
