name: Application Insights Native Metrics MacOS CI

on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [8.x,10.x, 12.x, 14.x, 15.x, 16.x, 17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          LINUX_CXX: g++-4.8
      - run: npm ci
      - run: npm run build:ts
      - run: npm run build
      - run: npm test
      - run: npm run publish:github
