name: Application Insights Native Metrics Node.js CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.x]
        # node-version: [8.x,10.x, 12.x, 14.x, 15.x, 16.x, 17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        env:
          LINUX_CXX: g++-4.8
      - run: npm ci
      - run: npm run build:ts
      - run: npm run build
      - run: npm test
      - run: npm install node-pre-gyp-github@1.4.3
      - run: ./node_modules/.bin/node-pre-gyp configure
      - run: ./node_modules/.bin/node-pre-gyp build
      - run: ./node_modules/.bin/node-pre-gyp package
      - run: ./node_modules/.bin/node-pre-gyp-github publish
