name: Application Insights Native Metrics Windows CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [8.x,10.x, 12.x, 14.x, 15.x, 16.x, 17.x]
    env:
      CXX: g++-4.8
      NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build:ts
      - run: npm run build
      - run: npm test
      - run: npm install node-pre-gyp-github@1.4.3
      - run: npm run publish:github

